[package]
name = "buildstr"
description = "Get the builder of your values as a String. Useful for macros."
keywords = ["buildstr", "builder", "string", ""]
version = "0.1.0"
edition = "2021"
authors = ["Liam Garriga <liam@garriga.dev>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buildstr_derive = { version = "0.1.0", optional = true, path = "../buildstr_derive" }
syn = { version = "2.0.29", optional = true, features = ["parsing"] }
prettier-please = { version = "0.2.0", optional = true }

[features]
default = ["derive", "prelude", "collections", "pretty"]
derive = ["buildstr_derive"]

pretty = ["syn", "prettier-please"]

prelude = ["primitives", "vec", "reference", "array", "tuple", "string", "option", "result", "box"]
primitives = []
reference = []
vec = []
array = []
tuple = []
string = []
option = []
result = []
box = []

collections = ["btree"]
btree = []