name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly-2023-09-04
            components: rustfmt, clippy, miri

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      
      - name: Test
        run: cargo +nightly miri test --all-features
