name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly-2023-09-04
            components: rustfmt, clippy, miri
            override: true
      
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      
      - name: Run tests
        run: cargo +nightly-2023-09-04 miri test --all-features
